src/Entity/FaccaoRomaneio.php
<?php

namespace App\Entity;

use App\Repository\FaccaoRomaneioRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FaccaoRomaneioRepository::class)
 */
class FaccaoRomaneio
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $faccao_code;

    /**
     * @ORM\Column(type="integer")
     */
    private $ordem_producao;

    /**
     * @ORM\Column(type="text")
     */
    private $grade;

    /**
     * @ORM\Column(type="text")
     */
    private $seguencia;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $deleted_at;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $romaneio_code;

    /**
     * @ORM\Column(type="integer")
     */
    private $faccao_status;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $status_updated;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $projecao_coleta;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $valor_faccao;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $iniciado;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $finalizado;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFaccaoCode(): ?string
    {
        return $this->faccao_code;
    }

    public function setFaccaoCode(string $faccao_code): self
    {
        $this->faccao_code = $faccao_code;

        return $this;
    }

    public function getOrdemProducao(): ?int
    {
        return $this->ordem_producao;
    }

    public function setOrdemProducao(int $ordem_producao): self
    {
        $this->ordem_producao = $ordem_producao;

        return $this;
    }

    public function getGrade(): ?string
    {
        return $this->grade;
    }

    public function setGrade(string $grade): self
    {
        $this->grade = $grade;

        return $this;
    }

    public function getSeguencia(): ?string
    {
        return $this->seguencia;
    }

    public function setSeguencia(string $seguencia): self
    {
        $this->seguencia = $seguencia;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeInterface
    {
        return $this->deleted_at;
    }

    public function setDeletedAt(?\DateTimeInterface $deleted_at): self
    {
        $this->deleted_at = $deleted_at;

        return $this;
    }

    /**
     * Get the value of romaneio_code
     */ 
    public function getRomaneioCode()
    {
        return $this->romaneio_code;
    }

    /**
     * Set the value of romaneio_code
     *
     * @return  self
     */ 
    public function setRomaneioCode($romaneio_code)
    {
        $this->romaneio_code = $romaneio_code;

        return $this;
    }

    public function getFaccaoStatus(): ?int
    {
        return $this->faccao_status;
    }

    public function setFaccaoStatus(int $faccao_status): self
    {
        $this->faccao_status = $faccao_status;

        return $this;
    }

    public function getStatusUpdated(): ?\DateTimeInterface
    {
        return $this->status_updated;
    }

    public function setStatusUpdated(?\DateTimeInterface $status_updated): self
    {
        $this->status_updated = $status_updated;

        return $this;
    }

    public function getProjecaoColeta(): ?\DateTimeInterface
    {
        return $this->projecao_coleta;
    }

    public function setProjecaoColeta(?\DateTimeInterface $projecao_coleta): self
    {
        $this->projecao_coleta = $projecao_coleta;

        return $this;
    }

    public function getValorFaccao(): ?string
    {
        return $this->valor_faccao;
    }

    public function setValorFaccao(string $valor_faccao): self
    {
        $this->valor_faccao = $valor_faccao;

        return $this;
    }

    public function getIniciado(): ?\DateTimeInterface
    {
        return $this->iniciado;
    }

    public function setIniciado(?\DateTimeInterface $iniciado): self
    {
        $this->iniciado = $iniciado;

        return $this;
    }

    public function getFinalizado(): ?\DateTimeInterface
    {
        return $this->finalizado;
    }

    public function setFinalizado(?\DateTimeInterface $finalizado): self
    {
        $this->finalizado = $finalizado;

        return $this;
    }
}

templates/finalizacao/finalizacao-show.html.twig
{% extends "base.html.twig" %}

{% block body %}
	{{ include('components/head/head.html.twig') }}
	{{ include('components/menu/menu-finalizacao.html.twig') }}
	<section class="container-first">

		<div class="box-model">
			<header class="menu-model">
				<b>Finalização - Ordem Produção:
					{{ response.ordemProducao }}
				</b>
			</header>
			<pre>
                
            </pre>
			{# romaneio: {{ dump(response.romaneioCode) }} #}
			<div class="box-model-check">

				<form id="form" name="registration" method="post" onsubmit="handlePost()" >
                    
                    <input type="hidden" name="romaneio_code" id="romaneio_code" value={{ response.romaneioCode }}>

					<div class="form-group">
						<input class="input-checked" type="radio" id="status-11" value="11" name="status" {{ response.faccaoStatus == '11' ? 'checked' : '' }} onclick="handleInput('status-11')">
						<label for="status-11">
							<b>Coletado</b>
						</label>
					</div>

					<div class="form-group">
						<input class="input-checked" type="radio" id="status-12" value="12" name="status" {{ response.faccaoStatus == '12' ? 'checked' : '' }} onclick="handleInput('status-12')">
						<label for="status-12">
							<b>Tag</b>
						</label>
					</div>

					<div class="form-group">
						<input class="input-checked" type="radio" id="status-13" value="13" name="status" {{ response.faccaoStatus == '13' ? 'checked' : '' }} onclick="handleInput('status-13')" >
						<label for="status-13">
							<b>Revisão</b>
						</label>
					</div>

					<div class="form-group">
						<input class="input-checked" type="radio" id="status-14" value="14" name="status" {{ response.faccaoStatus == '14' ? 'checked' : '' }} onclick="handleInput('status-14')" >
						<label for="status-14">
							<b>Flush</b>
						</label>
					</div>

					<div class="form-group">
						<input class="input-checked" type="radio" id="status-15" value="15" name="status" {{ response.faccaoStatus == '15' ? 'checked' : '' }} onclick="handleInput('status-15')" >
						<label for="status-15">
							<b>Tonalidade</b>
						</label>
					</div>

					<div class="form-group">
						<input class="input-checked" type="radio" id="status-16" value="16" name="status" {{ response.faccaoStatus == '16' ? 'checked' : '' }} onclick="handleInput('status-16')" >
						<label for="status-16">
							<b>Pronto para Embarque</b>
						</label>
					</div>
                    
				</form>

				<a class="link-bt" href="template/finalização">Cancelar</a>
				<button class="button" type="submit" id="btn-salvar" onclick="onSubmit()">Salvar</button>

			</div>

		</div>

	</div>

</section>{% endblock %}

templates/finalizacao/finalizacao.html.twig
{% extends "base.html.twig" %}

{% block body %}
	{{ include('components/head/head.html.twig') }}
	{{ include('components/menu/menu-finalizacao.html.twig') }}
	<section class="container-first">

		<div class="box-model">
			<header class="menu-model">
				<b>Finalização</b>
			</header>
			{# {{ dump(response) }} #}
			<div class="box-model-main">
                <div class="mt-20"></div>
				<ul class="ul-finalizacao">
					{% for item in response %}
						<li class="li-finalizacao">
							<a class="li-finalizacao-a" href="/template/finalizacao-get/{{ item.faccao_code }}/{{ item.ordem_producao }}">{{ item.ordem_producao }}</a>
						</li>
					{% endfor %}
				</ul>
			</div>

		</div>

	</section>
{% endblock %}